#!/bin/bash
# combustion: network
set -x

#set root password
echo 'root:$6$i8ri1WySrj.C6wlg$c708jMr/etTBFf.ZP41QY9l4WK9epDCN1CdbtRJUfhGvzLeL6Kr7hQhx0O5mFhGEvHG2LMm1a5pUYTBUDiIop/' | chpasswd -e

# enable and start the cockpit socket in systemd
systemctl enable cockpit.socket

# register with RMT
SUSEConnect --url http://rmt.example.com

# Install updates
zypper -n up

##### install k3s
mkdir -pv /root/bin/

#get the mac address. It will be the hostname in k3s
NAME=`ip a | grep ether | awk  '{print $2}'`

echo "set hostname"
hostname $NAME
echo $NAME > /etc/hostname

curl -sfL https://get.k3s.io | K3S_TOKEN=susetrainingdemotoken K3S_URL=https://node00.example.com:6443 INSTALL_K3S_BIN_DIR=/root/bin/ sh -

#chmod +x -v /root/bin/k3s
